using System;

class Program {
   public static void Main (string[] args) {
    Console.WriteLine ("\n[Intro]");
    Console.WriteLine ("Among us in real life");
    Console.WriteLine ("(Sus, sus)");
    Console.WriteLine ("Among us in real life");
    Console.WriteLine ("(Sus, sus)");
    Console.WriteLine ("\n[Verse 1]");
    Console.WriteLine ("Playing among us in real life");
    Console.WriteLine ("Spaceship with my crew");
    Console.WriteLine ("Gotta split up, spread out 'cause we all got tasks to do");
    Console.WriteLine ("Gotta find the impostor as they try to sabotage");
    Console.WriteLine ("Who can we trust in this Among Us entourage?");
    Console.WriteLine ("Heard a sound, turned around, looking up, looking down");
    Console.WriteLine ("Heard a sound, turned around, looking up, looking down");
    Console.WriteLine ("Then I find a dead body");
    Console.WriteLine ("Gotta blow the horn");
    Console.WriteLine ("emergency discussion, who should we believe?");
    Console.WriteLine ("Can't decide, so, now we leave, not sure what I'm about to see");
    Console.WriteLine ("Will it be a dead body? Still have a task I must complete");
    Console.WriteLine ("\n[Chorus]");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("\n[Verse 2]");
    Console.WriteLine ("I'm a ghost, I'm my biggest fear, got killed by the imposter");
    Console.WriteLine ("I was playing in the game, but now I'm just a watcher");
    Console.WriteLine ("I'm paying attention using my 360 vision");
    Console.WriteLine ("If it gets quiet, I listen");
    Console.WriteLine ("Make sure there's nothing I'm missing");
    Console.WriteLine ("\n[Chorus]");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("\n[Verse 3]");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("It wasn't me (or me)");
    Console.WriteLine ("It definitely wasn't me");
    Console.WriteLine ("No one can be trusted because someone is lying");
    Console.WriteLine ("We still have tasks to do, so, let's split up so we can win");
    Console.WriteLine ("Everyone is sus so let this last round begin");
    Console.WriteLine ("There's an imposter among us");
    Console.WriteLine ("Trying to take something from us");
    Console.WriteLine ("We're still over here working");
    Console.WriteLine ("While she's just ghosting above us");
    Console.WriteLine ("Someone's under suspicion");
    Console.WriteLine ("Sabotaging our mission");
    Console.WriteLine ("Doing my task in the kitchen");
    Console.WriteLine ("Until I stop, look, and listen");
    Console.WriteLine ("\n[Chorus]");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("Who's the impostor looking sus");
    Console.WriteLine ("\n[Verse 4]");
    Console.WriteLine ("I'm the I-M-P-O-S-T-E-R, that's me");
    Console.WriteLine ("Everyone's doing tasks, I'm going through vents on a killing spree");
    Console.WriteLine ("Yeah, I'm sus in Among Us");
    Console.WriteLine ("We can discuss whoever took your life");
    Console.WriteLine ("But if you think you're running this game, oh yeah");
    Console.WriteLine ("That's me holding this knife");
    Console.WriteLine ("\n[Sussy chorus]");
    Console.WriteLine ("I'm the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("I'm the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("I'm the impostor looking sus");
    Console.WriteLine ("Who can we trust?");
    Console.WriteLine ("I'm the impostor");
  }
}
